#ifndef __BADAPPLE_CONFIG_H
#define __BADAPPLE_CONFIG_H

#define BADAPPLE_AUDIO_DATA_SIZE   75502
#define BADAPPLE_AUDIO_DATA_OFFSET 1
#define BADAPPLE_VIDEO_DATA_SIZE   240225
#define BADAPPLE_VIDEO_DATA_OFFSET 102400

extern uint8_t badapple_loading_image[];

#endif
