.text
.globl __alltraps
.globl __trapvector0
__trapvector0:
  pushl $0
  pushl $0
  jmp __alltraps
.globl __trapvector1
__trapvector1:
  pushl $0
  pushl $1
  jmp __alltraps
.globl __trapvector2
__trapvector2:
  pushl $0
  pushl $2
  jmp __alltraps
.globl __trapvector3
__trapvector3:
  pushl $0
  pushl $3
  jmp __alltraps
.globl __trapvector4
__trapvector4:
  pushl $0
  pushl $4
  jmp __alltraps
.globl __trapvector5
__trapvector5:
  pushl $0
  pushl $5
  jmp __alltraps
.globl __trapvector6
__trapvector6:
  pushl $0
  pushl $6
  jmp __alltraps
.globl __trapvector7
__trapvector7:
  pushl $0
  pushl $7
  jmp __alltraps
.globl __trapvector8
__trapvector8:
  pushl $0
  pushl $8
  jmp __alltraps
.globl __trapvector9
__trapvector9:
  pushl $0
  pushl $9
  jmp __alltraps
.globl __trapvector10
__trapvector10:
  pushl $0
  pushl $10
  jmp __alltraps
.globl __trapvector11
__trapvector11:
  pushl $0
  pushl $11
  jmp __alltraps
.globl __trapvector12
__trapvector12:
  pushl $0
  pushl $12
  jmp __alltraps
.globl __trapvector13
__trapvector13:
  pushl $0
  pushl $13
  jmp __alltraps
.globl __trapvector14
__trapvector14:
  pushl $0
  pushl $14
  jmp __alltraps
.globl __trapvector15
__trapvector15:
  pushl $0
  pushl $15
  jmp __alltraps
.globl __trapvector16
__trapvector16:
  pushl $0
  pushl $16
  jmp __alltraps
.globl __trapvector17
__trapvector17:
  pushl $0
  pushl $17
  jmp __alltraps
.globl __trapvector18
__trapvector18:
  pushl $0
  pushl $18
  jmp __alltraps
.globl __trapvector19
__trapvector19:
  pushl $0
  pushl $19
  jmp __alltraps
.globl __trapvector20
__trapvector20:
  pushl $0
  pushl $20
  jmp __alltraps
.globl __trapvector21
__trapvector21:
  pushl $0
  pushl $21
  jmp __alltraps
.globl __trapvector22
__trapvector22:
  pushl $0
  pushl $22
  jmp __alltraps
.globl __trapvector23
__trapvector23:
  pushl $0
  pushl $23
  jmp __alltraps
.globl __trapvector24
__trapvector24:
  pushl $0
  pushl $24
  jmp __alltraps
.globl __trapvector25
__trapvector25:
  pushl $0
  pushl $25
  jmp __alltraps
.globl __trapvector26
__trapvector26:
  pushl $0
  pushl $26
  jmp __alltraps
.globl __trapvector27
__trapvector27:
  pushl $0
  pushl $27
  jmp __alltraps
.globl __trapvector28
__trapvector28:
  pushl $0
  pushl $28
  jmp __alltraps
.globl __trapvector29
__trapvector29:
  pushl $0
  pushl $29
  jmp __alltraps
.globl __trapvector30
__trapvector30:
  pushl $0
  pushl $30
  jmp __alltraps
.globl __trapvector31
__trapvector31:
  pushl $0
  pushl $31
  jmp __alltraps
.globl __trapvector32
__trapvector32:
  pushl $0
  pushl $32
  jmp __alltraps
.globl __trapvector33
__trapvector33:
  pushl $0
  pushl $33
  jmp __alltraps
.globl __trapvector34
__trapvector34:
  pushl $0
  pushl $34
  jmp __alltraps
.globl __trapvector35
__trapvector35:
  pushl $0
  pushl $35
  jmp __alltraps
.globl __trapvector36
__trapvector36:
  pushl $0
  pushl $36
  jmp __alltraps
.globl __trapvector37
__trapvector37:
  pushl $0
  pushl $37
  jmp __alltraps
.globl __trapvector38
__trapvector38:
  pushl $0
  pushl $38
  jmp __alltraps
.globl __trapvector39
__trapvector39:
  pushl $0
  pushl $39
  jmp __alltraps
.globl __trapvector40
__trapvector40:
  pushl $0
  pushl $40
  jmp __alltraps
.globl __trapvector41
__trapvector41:
  pushl $0
  pushl $41
  jmp __alltraps
.globl __trapvector42
__trapvector42:
  pushl $0
  pushl $42
  jmp __alltraps
.globl __trapvector43
__trapvector43:
  pushl $0
  pushl $43
  jmp __alltraps
.globl __trapvector44
__trapvector44:
  pushl $0
  pushl $44
  jmp __alltraps
.globl __trapvector45
__trapvector45:
  pushl $0
  pushl $45
  jmp __alltraps
.globl __trapvector46
__trapvector46:
  pushl $0
  pushl $46
  jmp __alltraps
.globl __trapvector47
__trapvector47:
  pushl $0
  pushl $47
  jmp __alltraps
.globl __trapvector48
__trapvector48:
  pushl $0
  pushl $48
  jmp __alltraps
.globl __trapvector49
__trapvector49:
  pushl $0
  pushl $49
  jmp __alltraps
.globl __trapvector50
__trapvector50:
  pushl $0
  pushl $50
  jmp __alltraps
.globl __trapvector51
__trapvector51:
  pushl $0
  pushl $51
  jmp __alltraps
.globl __trapvector52
__trapvector52:
  pushl $0
  pushl $52
  jmp __alltraps
.globl __trapvector53
__trapvector53:
  pushl $0
  pushl $53
  jmp __alltraps
.globl __trapvector54
__trapvector54:
  pushl $0
  pushl $54
  jmp __alltraps
.globl __trapvector55
__trapvector55:
  pushl $0
  pushl $55
  jmp __alltraps
.globl __trapvector56
__trapvector56:
  pushl $0
  pushl $56
  jmp __alltraps
.globl __trapvector57
__trapvector57:
  pushl $0
  pushl $57
  jmp __alltraps
.globl __trapvector58
__trapvector58:
  pushl $0
  pushl $58
  jmp __alltraps
.globl __trapvector59
__trapvector59:
  pushl $0
  pushl $59
  jmp __alltraps
.globl __trapvector60
__trapvector60:
  pushl $0
  pushl $60
  jmp __alltraps
.globl __trapvector61
__trapvector61:
  pushl $0
  pushl $61
  jmp __alltraps
.globl __trapvector62
__trapvector62:
  pushl $0
  pushl $62
  jmp __alltraps
.globl __trapvector63
__trapvector63:
  pushl $0
  pushl $63
  jmp __alltraps
.globl __trapvector64
__trapvector64:
  pushl $0
  pushl $64
  jmp __alltraps
.globl __trapvector65
__trapvector65:
  pushl $0
  pushl $65
  jmp __alltraps
.globl __trapvector66
__trapvector66:
  pushl $0
  pushl $66
  jmp __alltraps
.globl __trapvector67
__trapvector67:
  pushl $0
  pushl $67
  jmp __alltraps
.globl __trapvector68
__trapvector68:
  pushl $0
  pushl $68
  jmp __alltraps
.globl __trapvector69
__trapvector69:
  pushl $0
  pushl $69
  jmp __alltraps
.globl __trapvector70
__trapvector70:
  pushl $0
  pushl $70
  jmp __alltraps
.globl __trapvector71
__trapvector71:
  pushl $0
  pushl $71
  jmp __alltraps
.globl __trapvector72
__trapvector72:
  pushl $0
  pushl $72
  jmp __alltraps
.globl __trapvector73
__trapvector73:
  pushl $0
  pushl $73
  jmp __alltraps
.globl __trapvector74
__trapvector74:
  pushl $0
  pushl $74
  jmp __alltraps
.globl __trapvector75
__trapvector75:
  pushl $0
  pushl $75
  jmp __alltraps
.globl __trapvector76
__trapvector76:
  pushl $0
  pushl $76
  jmp __alltraps
.globl __trapvector77
__trapvector77:
  pushl $0
  pushl $77
  jmp __alltraps
.globl __trapvector78
__trapvector78:
  pushl $0
  pushl $78
  jmp __alltraps
.globl __trapvector79
__trapvector79:
  pushl $0
  pushl $79
  jmp __alltraps
.globl __trapvector80
__trapvector80:
  pushl $0
  pushl $80
  jmp __alltraps
.globl __trapvector81
__trapvector81:
  pushl $0
  pushl $81
  jmp __alltraps
.globl __trapvector82
__trapvector82:
  pushl $0
  pushl $82
  jmp __alltraps
.globl __trapvector83
__trapvector83:
  pushl $0
  pushl $83
  jmp __alltraps
.globl __trapvector84
__trapvector84:
  pushl $0
  pushl $84
  jmp __alltraps
.globl __trapvector85
__trapvector85:
  pushl $0
  pushl $85
  jmp __alltraps
.globl __trapvector86
__trapvector86:
  pushl $0
  pushl $86
  jmp __alltraps
.globl __trapvector87
__trapvector87:
  pushl $0
  pushl $87
  jmp __alltraps
.globl __trapvector88
__trapvector88:
  pushl $0
  pushl $88
  jmp __alltraps
.globl __trapvector89
__trapvector89:
  pushl $0
  pushl $89
  jmp __alltraps
.globl __trapvector90
__trapvector90:
  pushl $0
  pushl $90
  jmp __alltraps
.globl __trapvector91
__trapvector91:
  pushl $0
  pushl $91
  jmp __alltraps
.globl __trapvector92
__trapvector92:
  pushl $0
  pushl $92
  jmp __alltraps
.globl __trapvector93
__trapvector93:
  pushl $0
  pushl $93
  jmp __alltraps
.globl __trapvector94
__trapvector94:
  pushl $0
  pushl $94
  jmp __alltraps
.globl __trapvector95
__trapvector95:
  pushl $0
  pushl $95
  jmp __alltraps
.globl __trapvector96
__trapvector96:
  pushl $0
  pushl $96
  jmp __alltraps
.globl __trapvector97
__trapvector97:
  pushl $0
  pushl $97
  jmp __alltraps
.globl __trapvector98
__trapvector98:
  pushl $0
  pushl $98
  jmp __alltraps
.globl __trapvector99
__trapvector99:
  pushl $0
  pushl $99
  jmp __alltraps
.globl __trapvector100
__trapvector100:
  pushl $0
  pushl $100
  jmp __alltraps
.globl __trapvector101
__trapvector101:
  pushl $0
  pushl $101
  jmp __alltraps
.globl __trapvector102
__trapvector102:
  pushl $0
  pushl $102
  jmp __alltraps
.globl __trapvector103
__trapvector103:
  pushl $0
  pushl $103
  jmp __alltraps
.globl __trapvector104
__trapvector104:
  pushl $0
  pushl $104
  jmp __alltraps
.globl __trapvector105
__trapvector105:
  pushl $0
  pushl $105
  jmp __alltraps
.globl __trapvector106
__trapvector106:
  pushl $0
  pushl $106
  jmp __alltraps
.globl __trapvector107
__trapvector107:
  pushl $0
  pushl $107
  jmp __alltraps
.globl __trapvector108
__trapvector108:
  pushl $0
  pushl $108
  jmp __alltraps
.globl __trapvector109
__trapvector109:
  pushl $0
  pushl $109
  jmp __alltraps
.globl __trapvector110
__trapvector110:
  pushl $0
  pushl $110
  jmp __alltraps
.globl __trapvector111
__trapvector111:
  pushl $0
  pushl $111
  jmp __alltraps
.globl __trapvector112
__trapvector112:
  pushl $0
  pushl $112
  jmp __alltraps
.globl __trapvector113
__trapvector113:
  pushl $0
  pushl $113
  jmp __alltraps
.globl __trapvector114
__trapvector114:
  pushl $0
  pushl $114
  jmp __alltraps
.globl __trapvector115
__trapvector115:
  pushl $0
  pushl $115
  jmp __alltraps
.globl __trapvector116
__trapvector116:
  pushl $0
  pushl $116
  jmp __alltraps
.globl __trapvector117
__trapvector117:
  pushl $0
  pushl $117
  jmp __alltraps
.globl __trapvector118
__trapvector118:
  pushl $0
  pushl $118
  jmp __alltraps
.globl __trapvector119
__trapvector119:
  pushl $0
  pushl $119
  jmp __alltraps
.globl __trapvector120
__trapvector120:
  pushl $0
  pushl $120
  jmp __alltraps
.globl __trapvector121
__trapvector121:
  pushl $0
  pushl $121
  jmp __alltraps
.globl __trapvector122
__trapvector122:
  pushl $0
  pushl $122
  jmp __alltraps
.globl __trapvector123
__trapvector123:
  pushl $0
  pushl $123
  jmp __alltraps
.globl __trapvector124
__trapvector124:
  pushl $0
  pushl $124
  jmp __alltraps
.globl __trapvector125
__trapvector125:
  pushl $0
  pushl $125
  jmp __alltraps
.globl __trapvector126
__trapvector126:
  pushl $0
  pushl $126
  jmp __alltraps
.globl __trapvector127
__trapvector127:
  pushl $0
  pushl $127
  jmp __alltraps
.globl __trapvector128
__trapvector128:
  pushl $0
  pushl $128
  jmp __alltraps
.globl __trapvector129
__trapvector129:
  pushl $0
  pushl $129
  jmp __alltraps
.globl __trapvector130
__trapvector130:
  pushl $0
  pushl $130
  jmp __alltraps
.globl __trapvector131
__trapvector131:
  pushl $0
  pushl $131
  jmp __alltraps
.globl __trapvector132
__trapvector132:
  pushl $0
  pushl $132
  jmp __alltraps
.globl __trapvector133
__trapvector133:
  pushl $0
  pushl $133
  jmp __alltraps
.globl __trapvector134
__trapvector134:
  pushl $0
  pushl $134
  jmp __alltraps
.globl __trapvector135
__trapvector135:
  pushl $0
  pushl $135
  jmp __alltraps
.globl __trapvector136
__trapvector136:
  pushl $0
  pushl $136
  jmp __alltraps
.globl __trapvector137
__trapvector137:
  pushl $0
  pushl $137
  jmp __alltraps
.globl __trapvector138
__trapvector138:
  pushl $0
  pushl $138
  jmp __alltraps
.globl __trapvector139
__trapvector139:
  pushl $0
  pushl $139
  jmp __alltraps
.globl __trapvector140
__trapvector140:
  pushl $0
  pushl $140
  jmp __alltraps
.globl __trapvector141
__trapvector141:
  pushl $0
  pushl $141
  jmp __alltraps
.globl __trapvector142
__trapvector142:
  pushl $0
  pushl $142
  jmp __alltraps
.globl __trapvector143
__trapvector143:
  pushl $0
  pushl $143
  jmp __alltraps
.globl __trapvector144
__trapvector144:
  pushl $0
  pushl $144
  jmp __alltraps
.globl __trapvector145
__trapvector145:
  pushl $0
  pushl $145
  jmp __alltraps
.globl __trapvector146
__trapvector146:
  pushl $0
  pushl $146
  jmp __alltraps
.globl __trapvector147
__trapvector147:
  pushl $0
  pushl $147
  jmp __alltraps
.globl __trapvector148
__trapvector148:
  pushl $0
  pushl $148
  jmp __alltraps
.globl __trapvector149
__trapvector149:
  pushl $0
  pushl $149
  jmp __alltraps
.globl __trapvector150
__trapvector150:
  pushl $0
  pushl $150
  jmp __alltraps
.globl __trapvector151
__trapvector151:
  pushl $0
  pushl $151
  jmp __alltraps
.globl __trapvector152
__trapvector152:
  pushl $0
  pushl $152
  jmp __alltraps
.globl __trapvector153
__trapvector153:
  pushl $0
  pushl $153
  jmp __alltraps
.globl __trapvector154
__trapvector154:
  pushl $0
  pushl $154
  jmp __alltraps
.globl __trapvector155
__trapvector155:
  pushl $0
  pushl $155
  jmp __alltraps
.globl __trapvector156
__trapvector156:
  pushl $0
  pushl $156
  jmp __alltraps
.globl __trapvector157
__trapvector157:
  pushl $0
  pushl $157
  jmp __alltraps
.globl __trapvector158
__trapvector158:
  pushl $0
  pushl $158
  jmp __alltraps
.globl __trapvector159
__trapvector159:
  pushl $0
  pushl $159
  jmp __alltraps
.globl __trapvector160
__trapvector160:
  pushl $0
  pushl $160
  jmp __alltraps
.globl __trapvector161
__trapvector161:
  pushl $0
  pushl $161
  jmp __alltraps
.globl __trapvector162
__trapvector162:
  pushl $0
  pushl $162
  jmp __alltraps
.globl __trapvector163
__trapvector163:
  pushl $0
  pushl $163
  jmp __alltraps
.globl __trapvector164
__trapvector164:
  pushl $0
  pushl $164
  jmp __alltraps
.globl __trapvector165
__trapvector165:
  pushl $0
  pushl $165
  jmp __alltraps
.globl __trapvector166
__trapvector166:
  pushl $0
  pushl $166
  jmp __alltraps
.globl __trapvector167
__trapvector167:
  pushl $0
  pushl $167
  jmp __alltraps
.globl __trapvector168
__trapvector168:
  pushl $0
  pushl $168
  jmp __alltraps
.globl __trapvector169
__trapvector169:
  pushl $0
  pushl $169
  jmp __alltraps
.globl __trapvector170
__trapvector170:
  pushl $0
  pushl $170
  jmp __alltraps
.globl __trapvector171
__trapvector171:
  pushl $0
  pushl $171
  jmp __alltraps
.globl __trapvector172
__trapvector172:
  pushl $0
  pushl $172
  jmp __alltraps
.globl __trapvector173
__trapvector173:
  pushl $0
  pushl $173
  jmp __alltraps
.globl __trapvector174
__trapvector174:
  pushl $0
  pushl $174
  jmp __alltraps
.globl __trapvector175
__trapvector175:
  pushl $0
  pushl $175
  jmp __alltraps
.globl __trapvector176
__trapvector176:
  pushl $0
  pushl $176
  jmp __alltraps
.globl __trapvector177
__trapvector177:
  pushl $0
  pushl $177
  jmp __alltraps
.globl __trapvector178
__trapvector178:
  pushl $0
  pushl $178
  jmp __alltraps
.globl __trapvector179
__trapvector179:
  pushl $0
  pushl $179
  jmp __alltraps
.globl __trapvector180
__trapvector180:
  pushl $0
  pushl $180
  jmp __alltraps
.globl __trapvector181
__trapvector181:
  pushl $0
  pushl $181
  jmp __alltraps
.globl __trapvector182
__trapvector182:
  pushl $0
  pushl $182
  jmp __alltraps
.globl __trapvector183
__trapvector183:
  pushl $0
  pushl $183
  jmp __alltraps
.globl __trapvector184
__trapvector184:
  pushl $0
  pushl $184
  jmp __alltraps
.globl __trapvector185
__trapvector185:
  pushl $0
  pushl $185
  jmp __alltraps
.globl __trapvector186
__trapvector186:
  pushl $0
  pushl $186
  jmp __alltraps
.globl __trapvector187
__trapvector187:
  pushl $0
  pushl $187
  jmp __alltraps
.globl __trapvector188
__trapvector188:
  pushl $0
  pushl $188
  jmp __alltraps
.globl __trapvector189
__trapvector189:
  pushl $0
  pushl $189
  jmp __alltraps
.globl __trapvector190
__trapvector190:
  pushl $0
  pushl $190
  jmp __alltraps
.globl __trapvector191
__trapvector191:
  pushl $0
  pushl $191
  jmp __alltraps
.globl __trapvector192
__trapvector192:
  pushl $0
  pushl $192
  jmp __alltraps
.globl __trapvector193
__trapvector193:
  pushl $0
  pushl $193
  jmp __alltraps
.globl __trapvector194
__trapvector194:
  pushl $0
  pushl $194
  jmp __alltraps
.globl __trapvector195
__trapvector195:
  pushl $0
  pushl $195
  jmp __alltraps
.globl __trapvector196
__trapvector196:
  pushl $0
  pushl $196
  jmp __alltraps
.globl __trapvector197
__trapvector197:
  pushl $0
  pushl $197
  jmp __alltraps
.globl __trapvector198
__trapvector198:
  pushl $0
  pushl $198
  jmp __alltraps
.globl __trapvector199
__trapvector199:
  pushl $0
  pushl $199
  jmp __alltraps
.globl __trapvector200
__trapvector200:
  pushl $0
  pushl $200
  jmp __alltraps
.globl __trapvector201
__trapvector201:
  pushl $0
  pushl $201
  jmp __alltraps
.globl __trapvector202
__trapvector202:
  pushl $0
  pushl $202
  jmp __alltraps
.globl __trapvector203
__trapvector203:
  pushl $0
  pushl $203
  jmp __alltraps
.globl __trapvector204
__trapvector204:
  pushl $0
  pushl $204
  jmp __alltraps
.globl __trapvector205
__trapvector205:
  pushl $0
  pushl $205
  jmp __alltraps
.globl __trapvector206
__trapvector206:
  pushl $0
  pushl $206
  jmp __alltraps
.globl __trapvector207
__trapvector207:
  pushl $0
  pushl $207
  jmp __alltraps
.globl __trapvector208
__trapvector208:
  pushl $0
  pushl $208
  jmp __alltraps
.globl __trapvector209
__trapvector209:
  pushl $0
  pushl $209
  jmp __alltraps
.globl __trapvector210
__trapvector210:
  pushl $0
  pushl $210
  jmp __alltraps
.globl __trapvector211
__trapvector211:
  pushl $0
  pushl $211
  jmp __alltraps
.globl __trapvector212
__trapvector212:
  pushl $0
  pushl $212
  jmp __alltraps
.globl __trapvector213
__trapvector213:
  pushl $0
  pushl $213
  jmp __alltraps
.globl __trapvector214
__trapvector214:
  pushl $0
  pushl $214
  jmp __alltraps
.globl __trapvector215
__trapvector215:
  pushl $0
  pushl $215
  jmp __alltraps
.globl __trapvector216
__trapvector216:
  pushl $0
  pushl $216
  jmp __alltraps
.globl __trapvector217
__trapvector217:
  pushl $0
  pushl $217
  jmp __alltraps
.globl __trapvector218
__trapvector218:
  pushl $0
  pushl $218
  jmp __alltraps
.globl __trapvector219
__trapvector219:
  pushl $0
  pushl $219
  jmp __alltraps
.globl __trapvector220
__trapvector220:
  pushl $0
  pushl $220
  jmp __alltraps
.globl __trapvector221
__trapvector221:
  pushl $0
  pushl $221
  jmp __alltraps
.globl __trapvector222
__trapvector222:
  pushl $0
  pushl $222
  jmp __alltraps
.globl __trapvector223
__trapvector223:
  pushl $0
  pushl $223
  jmp __alltraps
.globl __trapvector224
__trapvector224:
  pushl $0
  pushl $224
  jmp __alltraps
.globl __trapvector225
__trapvector225:
  pushl $0
  pushl $225
  jmp __alltraps
.globl __trapvector226
__trapvector226:
  pushl $0
  pushl $226
  jmp __alltraps
.globl __trapvector227
__trapvector227:
  pushl $0
  pushl $227
  jmp __alltraps
.globl __trapvector228
__trapvector228:
  pushl $0
  pushl $228
  jmp __alltraps
.globl __trapvector229
__trapvector229:
  pushl $0
  pushl $229
  jmp __alltraps
.globl __trapvector230
__trapvector230:
  pushl $0
  pushl $230
  jmp __alltraps
.globl __trapvector231
__trapvector231:
  pushl $0
  pushl $231
  jmp __alltraps
.globl __trapvector232
__trapvector232:
  pushl $0
  pushl $232
  jmp __alltraps
.globl __trapvector233
__trapvector233:
  pushl $0
  pushl $233
  jmp __alltraps
.globl __trapvector234
__trapvector234:
  pushl $0
  pushl $234
  jmp __alltraps
.globl __trapvector235
__trapvector235:
  pushl $0
  pushl $235
  jmp __alltraps
.globl __trapvector236
__trapvector236:
  pushl $0
  pushl $236
  jmp __alltraps
.globl __trapvector237
__trapvector237:
  pushl $0
  pushl $237
  jmp __alltraps
.globl __trapvector238
__trapvector238:
  pushl $0
  pushl $238
  jmp __alltraps
.globl __trapvector239
__trapvector239:
  pushl $0
  pushl $239
  jmp __alltraps
.globl __trapvector240
__trapvector240:
  pushl $0
  pushl $240
  jmp __alltraps
.globl __trapvector241
__trapvector241:
  pushl $0
  pushl $241
  jmp __alltraps
.globl __trapvector242
__trapvector242:
  pushl $0
  pushl $242
  jmp __alltraps
.globl __trapvector243
__trapvector243:
  pushl $0
  pushl $243
  jmp __alltraps
.globl __trapvector244
__trapvector244:
  pushl $0
  pushl $244
  jmp __alltraps
.globl __trapvector245
__trapvector245:
  pushl $0
  pushl $245
  jmp __alltraps
.globl __trapvector246
__trapvector246:
  pushl $0
  pushl $246
  jmp __alltraps
.globl __trapvector247
__trapvector247:
  pushl $0
  pushl $247
  jmp __alltraps
.globl __trapvector248
__trapvector248:
  pushl $0
  pushl $248
  jmp __alltraps
.globl __trapvector249
__trapvector249:
  pushl $0
  pushl $249
  jmp __alltraps
.globl __trapvector250
__trapvector250:
  pushl $0
  pushl $250
  jmp __alltraps
.globl __trapvector251
__trapvector251:
  pushl $0
  pushl $251
  jmp __alltraps
.globl __trapvector252
__trapvector252:
  pushl $0
  pushl $252
  jmp __alltraps
.globl __trapvector253
__trapvector253:
  pushl $0
  pushl $253
  jmp __alltraps
.globl __trapvector254
__trapvector254:
  pushl $0
  pushl $254
  jmp __alltraps
.globl __trapvector255
__trapvector255:
  pushl $0
  pushl $255
  jmp __alltraps

.data
.globl __trapvectors
__trapvectors:
  .long __trapvector0
  .long __trapvector1
  .long __trapvector2
  .long __trapvector3
  .long __trapvector4
  .long __trapvector5
  .long __trapvector6
  .long __trapvector7
  .long __trapvector8
  .long __trapvector9
  .long __trapvector10
  .long __trapvector11
  .long __trapvector12
  .long __trapvector13
  .long __trapvector14
  .long __trapvector15
  .long __trapvector16
  .long __trapvector17
  .long __trapvector18
  .long __trapvector19
  .long __trapvector20
  .long __trapvector21
  .long __trapvector22
  .long __trapvector23
  .long __trapvector24
  .long __trapvector25
  .long __trapvector26
  .long __trapvector27
  .long __trapvector28
  .long __trapvector29
  .long __trapvector30
  .long __trapvector31
  .long __trapvector32
  .long __trapvector33
  .long __trapvector34
  .long __trapvector35
  .long __trapvector36
  .long __trapvector37
  .long __trapvector38
  .long __trapvector39
  .long __trapvector40
  .long __trapvector41
  .long __trapvector42
  .long __trapvector43
  .long __trapvector44
  .long __trapvector45
  .long __trapvector46
  .long __trapvector47
  .long __trapvector48
  .long __trapvector49
  .long __trapvector50
  .long __trapvector51
  .long __trapvector52
  .long __trapvector53
  .long __trapvector54
  .long __trapvector55
  .long __trapvector56
  .long __trapvector57
  .long __trapvector58
  .long __trapvector59
  .long __trapvector60
  .long __trapvector61
  .long __trapvector62
  .long __trapvector63
  .long __trapvector64
  .long __trapvector65
  .long __trapvector66
  .long __trapvector67
  .long __trapvector68
  .long __trapvector69
  .long __trapvector70
  .long __trapvector71
  .long __trapvector72
  .long __trapvector73
  .long __trapvector74
  .long __trapvector75
  .long __trapvector76
  .long __trapvector77
  .long __trapvector78
  .long __trapvector79
  .long __trapvector80
  .long __trapvector81
  .long __trapvector82
  .long __trapvector83
  .long __trapvector84
  .long __trapvector85
  .long __trapvector86
  .long __trapvector87
  .long __trapvector88
  .long __trapvector89
  .long __trapvector90
  .long __trapvector91
  .long __trapvector92
  .long __trapvector93
  .long __trapvector94
  .long __trapvector95
  .long __trapvector96
  .long __trapvector97
  .long __trapvector98
  .long __trapvector99
  .long __trapvector100
  .long __trapvector101
  .long __trapvector102
  .long __trapvector103
  .long __trapvector104
  .long __trapvector105
  .long __trapvector106
  .long __trapvector107
  .long __trapvector108
  .long __trapvector109
  .long __trapvector110
  .long __trapvector111
  .long __trapvector112
  .long __trapvector113
  .long __trapvector114
  .long __trapvector115
  .long __trapvector116
  .long __trapvector117
  .long __trapvector118
  .long __trapvector119
  .long __trapvector120
  .long __trapvector121
  .long __trapvector122
  .long __trapvector123
  .long __trapvector124
  .long __trapvector125
  .long __trapvector126
  .long __trapvector127
  .long __trapvector128
  .long __trapvector129
  .long __trapvector130
  .long __trapvector131
  .long __trapvector132
  .long __trapvector133
  .long __trapvector134
  .long __trapvector135
  .long __trapvector136
  .long __trapvector137
  .long __trapvector138
  .long __trapvector139
  .long __trapvector140
  .long __trapvector141
  .long __trapvector142
  .long __trapvector143
  .long __trapvector144
  .long __trapvector145
  .long __trapvector146
  .long __trapvector147
  .long __trapvector148
  .long __trapvector149
  .long __trapvector150
  .long __trapvector151
  .long __trapvector152
  .long __trapvector153
  .long __trapvector154
  .long __trapvector155
  .long __trapvector156
  .long __trapvector157
  .long __trapvector158
  .long __trapvector159
  .long __trapvector160
  .long __trapvector161
  .long __trapvector162
  .long __trapvector163
  .long __trapvector164
  .long __trapvector165
  .long __trapvector166
  .long __trapvector167
  .long __trapvector168
  .long __trapvector169
  .long __trapvector170
  .long __trapvector171
  .long __trapvector172
  .long __trapvector173
  .long __trapvector174
  .long __trapvector175
  .long __trapvector176
  .long __trapvector177
  .long __trapvector178
  .long __trapvector179
  .long __trapvector180
  .long __trapvector181
  .long __trapvector182
  .long __trapvector183
  .long __trapvector184
  .long __trapvector185
  .long __trapvector186
  .long __trapvector187
  .long __trapvector188
  .long __trapvector189
  .long __trapvector190
  .long __trapvector191
  .long __trapvector192
  .long __trapvector193
  .long __trapvector194
  .long __trapvector195
  .long __trapvector196
  .long __trapvector197
  .long __trapvector198
  .long __trapvector199
  .long __trapvector200
  .long __trapvector201
  .long __trapvector202
  .long __trapvector203
  .long __trapvector204
  .long __trapvector205
  .long __trapvector206
  .long __trapvector207
  .long __trapvector208
  .long __trapvector209
  .long __trapvector210
  .long __trapvector211
  .long __trapvector212
  .long __trapvector213
  .long __trapvector214
  .long __trapvector215
  .long __trapvector216
  .long __trapvector217
  .long __trapvector218
  .long __trapvector219
  .long __trapvector220
  .long __trapvector221
  .long __trapvector222
  .long __trapvector223
  .long __trapvector224
  .long __trapvector225
  .long __trapvector226
  .long __trapvector227
  .long __trapvector228
  .long __trapvector229
  .long __trapvector230
  .long __trapvector231
  .long __trapvector232
  .long __trapvector233
  .long __trapvector234
  .long __trapvector235
  .long __trapvector236
  .long __trapvector237
  .long __trapvector238
  .long __trapvector239
  .long __trapvector240
  .long __trapvector241
  .long __trapvector242
  .long __trapvector243
  .long __trapvector244
  .long __trapvector245
  .long __trapvector246
  .long __trapvector247
  .long __trapvector248
  .long __trapvector249
  .long __trapvector250
  .long __trapvector251
  .long __trapvector252
  .long __trapvector253
  .long __trapvector254
